#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then
    PYTHON_VERS="3.3.2"
    PIP_VERS="1.4.1"

    # install python on builder gear
    cd $OPENSHIFT_TMP_DIR
    wget http://python.org/ftp/python/${PYTHON_VERS}/Python-${PYTHON_VERS}.tar.xz
    tar Jxf Python-${PYTHON_VERS}.tar.xz
    cd Python-${PYTHON_VERS}
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make install

    export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH

    # install setuptools
    cd $OPENSHIFT_TMP_DIR
    wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
    python ez_setup.py --user

    # install pip
    cd $OPENSHIFT_TMP_DIR
    wget https://pypi.python.org/packages/source/p/pip/pip-${PIP_VERS}.tar.gz
    tar zxf pip-${PIP_VERS}.tar.gz
    cd pip-${PIP_VERS}
    python setup.py install

    # install uWSGI
    cd $OPENSHIFT_TMP_DIR
    pip install uwsgi

    # cleanup
    cd $OPENSHIFT_TMP_DIR
    rm -rf Python-${PYTHON_VERS}.tar.bz2
    rm -rf ez_setup.py
    rm -rf pip-${PIP_VERS}.tar.gz
fi
