#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then
    PYTHON_VERS="3.3.2"

    # install python on builder gear
    cd $OPENSHIFT_TMP_DIR
    wget http://python.org/ftp/python/${PYTHON_VERS}/Python-${PYTHON_VERS}.tar.xz
    tar Jxf Python-${PYTHON_VERS}.tar.xz
    cd Python-${PYTHON_VERS}
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make install

    export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH

    # symlink python -> python3
    ln -s $OPENSHIFT_DATA_DIR/python{3,}

    cd $OPENSHIFT_TMP_DIR
    # install setuptools and pip
    wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python
    wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py -O - | python
    pip install --upgrade setuptools
    # install uWSGI
    pip install uwsgi

    # cleanup
    cd $OPENSHIFT_TMP_DIR
    rm -rf Python-${PYTHON_VERS}.tar.bz2
    rm -rf ez_setup.py
    rm -rf get-pip.py
fi
